export const HOST = "http://localhost:8080";

export const REGISTER_URI = '/register';
export const LOGIN_URI = '/login';
export const PARTY_URI = '/party';

// Errors
export const GET_ERRORS = "GET_ERRORS";

// Login
export const ATTEMPT_LOGIN_FAILED = "ATTEMPT_REGISTER_FAILED";
export const ATTEMPT_LOGIN_SUCCESSFULLY = "ATTEMPT_REGISTER_SUCCESSFULLY";

export const GET_USER_IDENTITY = "GET_USER_IDENTITY";
export const GET_USER_IDENTITY_FAILED = "GET_USER_IDENTITY_FAILED";
export const GET_USER_IDENTITY_SUCCESSFULLY = "GET_USER_IDENTITY_SUCCESSFULLY";
export const TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND";

// Identity
export const USER_ID = "userID";
export const NULL_ID = "NULL_ID";
export const SET_USER_ID = "SET_USER_ID";
export const ATTEMPT_REGISTER_FAILED = 'ATTEMPT_REGISTER_FAILED';
export const ATTEMPT_REGISTER_SUCCESSFULLY = 'ATTEMPT_REGISTER_SUCCESSFULLY';

// Party
export const ATTEMPT_GET_PARTY_MEMBERS_FAILED = 'ATTEMPT_GET_PARTY_MEMBERS_FAILED';
export const ATTEMPT_GET_PARTY_MEMBERS_SUCCESSFULLY = 'ATTEMPT_GET_PARTY_MEMBERS_SUCCESSFULLY';
export const ATTEMPT_GET_PARTY_EVENTS_FAILED = 'ATTEMPT_GET_PARTY_EVENTS_FAILED';
export const ATTEMPT_GET_PARTY_EVENTS_SUCCESSFULLY = 'ATTEMPT_GET_PARTY_EVENTS_SUCCESSFULLY';
export const ATTEMPT_INVITE_PARTY_MEMBER_FAILED = 'ATTEMPT_INVITE_PARTY_MEMBER_FAILED';
export const ATTEMPT_INVITE_PARTY_MEMBER_SUCCESSFULLY = 'ATTEMPT_INVITE_PARTY_MEMBER_SUCCESSFULLY';
