export const HOST = 'http://localhost:8080';

export const REGISTER_URI = '/register';
export const LOGIN_URI = '/login';
export const EVENT_URI = '/event';
export const PARTY_URI = '/party';

// Errors
export const GET_ERRORS = 'GET_ERRORS';

// Register
export const ATTEMPT_REGISTER_FAILED = 'ATTEMPT_REGISTER_FAILED';
export const ATTEMPT_REGISTER_SUCCESSFULLY = 'ATTEMPT_REGISTER_SUCCESSFULLY';

// Create Group
export const ATTEMPT_CREATE_GROUP_FAILED = 'ATTEMPT_CREATE_GROUP_FAILED';
export const ATTEMPT_CREATE_GROUP_SUCCESSFULLY =
  'ATTEMPT_CREATE_GROUP_SUCCESSFULLY';

// Create Event
export const ATTEMPT_CREATE_EVENT_FAILED = 'ATTEMPT_CREATE_EVENT_FAILED';
export const ATTEMPT_CREATE_EVENT_SUCCESSFULLY =
  'ATTEMPT_CREATE_EVENT_SUCCESSFULLY';

// Login
export const ATTEMPT_LOGIN_FAILED = 'ATTEMPT_LOGIN_FAILED';
export const ATTEMPT_LOGIN_SUCCESSFULLY = 'ATTEMPT_LOGIN_SUCCESSFULLY';

export const ATTEMPT_LOGOUT = 'ATTEMPT_LOGOUT';

// Get Event Detail
export const ATTEMPT_GET_EVENT_DETAIL_FAILED =
  'ATTEMPT_GET_EVENT_DETAIL_FAILED';
export const ATTEMPT_GET_EVENT_DETAIL_SUCCESSFULLY =
  'ATTEMPT_GET_EVENT_DETAIL_SUCCESSFULLY';

// Calculate the split
export const ATTEMPT_CALCULATE_FAILED = 'ATTEMPT_CALCULATE_FAILED';
export const ATTEMPT_CALCULATE_SUCCESSFULLY = 'ATTEMPT_CALCULATE_SUCCESSFULLY';

// Contribute to Event
export const ATTEMPT_CONTRIBUTE_FAILED = 'ATTEMPT_CONTRIBUTE_FAILED';
export const ATTEMPT_CONTRIBUTE_SUCCESSFULLY =
  'ATTEMPT_CONTRIBUTE_SUCCESSFULLY';
export const GET_USER_IDENTITY = 'GET_USER_IDENTITY';
export const GET_USER_IDENTITY_FAILED = 'GET_USER_IDENTITY_FAILED';
export const GET_USER_IDENTITY_SUCCESSFULLY = 'GET_USER_IDENTITY_SUCCESSFULLY';
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND';

// Identity
export const USER_ID = "userID";
export const NULL_ID = "NULL_ID";
export const SET_USER_ID = "SET_USER_ID";

// Party
export const ATTEMPT_GET_PARTY_MEMBERS_FAILED = 'ATTEMPT_GET_PARTY_MEMBERS_FAILED';
export const ATTEMPT_GET_PARTY_MEMBERS_SUCCESSFULLY = 'ATTEMPT_GET_PARTY_MEMBERS_SUCCESSFULLY';
export const ATTEMPT_GET_PARTY_EVENTS_FAILED = 'ATTEMPT_GET_PARTY_EVENTS_FAILED';
export const ATTEMPT_GET_PARTY_EVENTS_SUCCESSFULLY = 'ATTEMPT_GET_PARTY_EVENTS_SUCCESSFULLY';
export const ATTEMPT_INVITE_PARTY_MEMBER_FAILED = 'ATTEMPT_INVITE_PARTY_MEMBER_FAILED';
export const ATTEMPT_INVITE_PARTY_MEMBER_SUCCESSFULLY = 'ATTEMPT_INVITE_PARTY_MEMBER_SUCCESSFULLY';
export const ATTEMPT_DELETE_USER_FROM_PARTY_FAILED = 'ATTEMPT_DELETE_USER_FROM_PARTY_FAILED';
export const ATTEMPT_DELETE_USER_FROM_PARTY_SUCCESSFULLY = 'ATTEMPT_DELETE_USER_FROM_PARTY_SUCCESSFULLY';
export const ATTEMPT_CREATE_PARTY_EVENT_FAILED = 'ATTEMPT_CREATE_PARTY_EVENT_FAILED';
export const ATTEMPT_CREATE_PARTY_EVENT_SUCCESSFULLY = 'ATTEMPT_CREATE_PARTY_EVENT_SUCCESSFULLY';

// HomePage
export const ATTEMPT_GET_EVENTS_BY_USERID_SUCCESSFULLY =
  'ATTEMPT_GET_EVENTS_BY_USERID_SUCCESSFULLY';
export const ATTEMPT_GET_EVENTS_BY_USERID_FAILED =
  'ATTEMPT_GET_EVENTS_BY_USERID_FAILED';

export const ATTEMPT_GET_PARTIES_BY_USERID_SUCCESSFULLY =
  'ATTEMPT_GET_PARTIES_BY_USERID_SUCCESSFULLY';
export const ATTEMPT_GET_PARTIES_BY_USERID_FAILED =
  'ATTEMPT_GET_PARTIES_BY_USERID_FAILED';
